--Q1

SELECT UPPER(CITY) FROM HR.LOCATIONS WHERE COUNTRY_ID = 'US';

--Q2  -- Added ',' for readability

SELECT UPPER(STREET_ADDRESS), LOWER(CITY), CONCAT(CONCAT(CITY, ', '), STATE_PROVINCE) AS CITY_STATE_PROVINCE FROM HR.LOCATIONS;

--Q3 

SELECT * FROM HR.EMPLOYEES WHERE LOWER(FIRST_NAME) = 'michael';

--Q4

SELECT INITCAP(FIRST_NAME) AS First_Name, INITCAP(LAST_NAME) AS Last_Name FROM HR.EMPLOYEES;

--Q5 

SELECT CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME) AS FULL_NAME, JOB_ID, MANAGER_ID FROM HR.EMPLOYEES;

--Q6

--TEST-- SELECT * FROM HR.EMPLOYEES WHERE JOB_ID LIKE 'FI%' OR JOB_ID LIKE '%CLERK'
SELECT * FROM HR.EMPLOYEES WHERE (SUBSTR(JOB_ID, 1, 2) = 'FI') OR (SUBSTR(JOB_ID, LENGTH(JOB_ID)-4, 5) = 'CLERK');

--Q7

SELECT FIRST_NAME, LAST_NAME, LENGTH(PHONE_NUMBER) AS PHONE_FORMAT, LENGTH(SALARY) AS SALARY_DIGITS FROM HR.EMPLOYEES;

--Q8

SELECT INSTR(JOB_TITLE, ' ') AS SPACE_LOCATION FROM HR.JOBS;

--Q9

-- TEST -- SELECT JOB_TITLE FROM HR.JOBS;
SELECT SUBSTR(JOB_TITLE, 0, INSTR(JOB_TITLE, ' ')) FROM HR.JOBS;

--Q10

SELECT LPAD('HELLO', 7, '^') FROM DUAL;

--Q11

SELECT RPAD('DATA', 7, '<') FROM DUAL;

--Q12

SELECT TRIM('  SHAZAIN  ') FROM DUAL;

--Q13

SELECT LTRIM('     SHAZAIN') FROM DUAL; 

--Q14

SELECT RTRIM('SHAZAIN     ') FROM DUAL;

--Q15

SELECT REPLACE('GOLDSMITH', 'GOLD', 'BLACK') FROM DUAL;

--Q16

SELECT ROUND(3.14159, 3) FROM DUAL;

--Q17

SELECT ROUND(3.14159, 0) FROM DUAL;

--Q18

SELECT TRUNC(3.1415926535897, 4) FROM DUAL;

--Q19

SELECT MOD(22, 13) FROM DUAL;

--Q20

SELECT MONTHS_BETWEEN(CURRENT_DATE, DATE'2003-12-10') FROM DUAL;

--Q21 

SELECT FIRST_NAME, LAST_NAME, JOB_ID, MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12, 2 AS EXPERIENCE_IN_YEARS FROM HR.EMPLOYEES;

--Q22

SELECT ADD_MONTHS(DATE'2024-08-29', 4) FROM DUAL;

--Q23

SELECT NEXT_DAY(DATE'2100-01-01', 'SUNDAY') FROM DUAL;

--Q24

SELECT ROUND(SYSDATE, 'MM') FROM DUAL;

--Q25

SELECT ROUND(SYSDATE, 'YY') FROM DUAL;

--Q26

SELECT TRUNC(SYSDATE, 'MM') FROM DUAL;

--Q27

SELECT TRUNC(SYSDATE, 'YY') FROM DUAL;

--Q28

SELECT COUNT(*) FROM HR.EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'MM') = 06;
