--Q1 

SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

--Q2 

SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 80 AND SALARY > 24000;

--Q3

SELECT COUNT(*) FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL

--Q4 

SELECT ROUND(AVG(salary), 2) AS AVERAGE, ROUND(MIN(salary), 2) AS MINIMUM, ROUND(MAX(salary), 2) AS MAXIMUM FROM EMPLOYEES WHERE JOB_ID LIKE '%CLERK';

--Q5

SELECT COUNT(DISTINCT(DEPARTMENT_ID)) FROM EMPLOYEES;

--Q6

SELECT COUNT(DISTINCT(EMPLOYEE_ID)) FROM EMPLOYEES;

--Q7

SELECT ROUND(AVG(COMMISSION_PCT), 2) FROM EMPLOYEES;

--Q8

SELECT ROUND(AVG(COMMISSION_PCT), 2) FROM EMPLOYEES;

--Q9

SELECT TRUNC((SUM(COMMISSION_PCT)/COUNT(*)), 2) FROM EMPLOYEES;

--Q10

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--Q11

SELECT JOB_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY JOB_ID;

--Q12

SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

--Q13

SELECT DEPARTMENT_ID, SUM(SALARY) AS SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY SALARY ASC FETCH FIRST 1 ROWS ONLY;

--Q14

SELECT JOB_ID AS JOB, MAX(SALARY) AS TOP_SALARIES FROM EMPLOYEES GROUP BY JOB_ID ORDER BY TOP_SALARIES DESC FETCH FIRST 5 ROWS ONLY;

--Q15

SELECT DEPARTMENT_ID, COUNT(LAST_NAME) FROM EMPLOYEES GROUP BY DEPARTMENT_ID

--Q16

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES HAVING AVG(SALARY) > 8000 GROUP BY DEPARTMENT_ID;

--Q17

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY (DEPARTMENT_ID, JOB_ID) HAVING SUM(SALARY) > 10000 ORDER BY DEPARTMENT_ID; 

--Q18

SELECT DEPARTMENT_ID, ROUND(AVG(MONTHS_BETWEEN(END_DATE, START_DATE)), 2) AS AVERAGE_MONTHS FROM JOB_HISTORY GROUP BY DEPARTMENT_ID;

--Q19

SELECT JOB_ID, MAX(MONTHS_BETWEEN(END_DATE, START_DATE)) AS MAXIMUM_DURATION FROM JOB_HISTORY GROUP BY JOB_ID ORDER BY MAXIMUM_DURATION DESC FETCH FIRST 1 ROWS ONLY;

--Q20

SELECT COUNTRY_ID, COUNT(LOCATION_ID) AS SUM_OF_LOCATIONS FROM LOCATIONS GROUP BY COUNTRY_ID;